### ISSUE TITLE
Read documentation - overview

### ISSUE THREAD

**Issue by yeungegs** [yeungegs/holbertonschool_big-o#9]
- [ ] https://en.wikipedia.org/wiki/Sorting_algorithm

- [ ] https://stackoverflow.com/questions/487258/what-is-a-plain-english-explanation-of-big-o-notation

- [ ] https://www.youtube.com/watch?v=kPRA0W1kECg

- [ ] https://www.toptal.com/developers/sorting-algorithms

**Comment by hicarrie** [comment]
read overview documentation first then individual documentation for each problem (because it's easier to digest!)

**Comment by yeungegs** [comment]
https://visualgo.net/en/sorting
